// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mveanyvsnyiocxffeogh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12ZWFueXZzbnlpb2N4ZmZlb2doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODQzMjMsImV4cCI6MjA2NjQ2MDMyM30.zIu07StG7hkUyb_VxbroAu8CMU63DrKDWM8Q7TnSedg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);